---
directories:
  'app/controllers':
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    UtilityFunction:
      public_methods_only: true
  'app/helpers':
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  'app/mailers':
    InstanceVariableAssumption:
      enabled: false
  'app/models':
    InstanceVariableAssumption:
      enabled: false
  'db/migrate':
    TooManyStatements:
      enabled: false

exclude_paths:
  - bin
  - config
  - db
  - node_modules
  - public
  - scripts
  - tmp
  - vendor
