inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml
require:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/**/*'
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7.4

Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - public_attribute_macros
    - public_delegate
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods
Layout/LineLength:
  Max: 120
